---
- hosts: all
  become: yes
  tasks:
  - ec2:
      aws_access_key: 
      aws_secret_key:
      instance_ids:
      group: Ansible_SG
      region: us-west-2
      state: stopped
      vpc_subnet_id: 
      assign_public_ip: yes
