---
- hosts: all
  become: yes
  tasks: 
  - ec2_vol:
      aws_access_key:
      aws_secret_key:
      instance:
      id:
      device_name: /dev/sdb1
      zone: us-west-2a
      region: us-west-2
      delete_on termination: yes