---
- hosts: all
  become: yes
  vars:
    keypair: ansible-key
    security_group: ansible-sg
    image:
    region: us-west-2
    type: t2.micro
  tasks:
  - ec2:
      aws_access_key: 
      aws_secret_key:
      key_name:
      group: Ansible_SG
      instance_type: t2.micro
      image:
      wait: yes
      wait_timeout: 500
      count: 3
      instance_tags:
        name: prod-instance
      monitoring: yes
      region: us-west-2
      vpc_subnet_id: 
      assign_public_ip: yes
