--- 
- hosts: all
  become: yes 
  tasks: 
  - name: create user and /etc/group
    user:
      name: "{{item.username}}"
      state: present
      group: "{{item.groupname}}"
    with_items:
      - { username: 'naresh',groupname: 'dev-team'}
      - { username: 'suresh',groupname: 'test-team'}
      - { username: 'ramesh',groupname: 'prod-team'}
      
