---
- hosts: 172.31.23.86
  become: yes
  tasks:
  - name: to install softwares
    apt: 
      name: "{{ item }}" 
      update_cache: yes
      state: present

    with_items:  
      - apache2
      - wget
      - tree
      - nfs-kernal-server