---
- hosts: all
  become: yes
  tasks:
  - name: to install softwares
    apt: 
      name: "{{item}}" 
      state: present
    with_items:  
      - apache2
      - wget
      - tree
      - nfs-kernal-server