---
- hosts: 172.31.23.86
  become: yes
  tasks:
   - name: to copy the files
     copy:
       src: "{{ item }}"
       dest: /tmp
  with_items:
   - /etc/passwd
   - /etc/group
   - /etc/fstap
   - /etc/shodow

  

      
