
---
- hosts: all
  become: yes
  tasks:
  - name: to create file
    file: path=/tmp/anji
          state=directory
  - name: to copy the file
    copy: src=ram
          dest=/tmp/bhanu
  - name: to install wget
    apt: name=wget
         state=present
         


 