---
- hosts: all
  become: yes
  tasks:
  - incloud_tasks: myloop1.yml
  - name:
    copy: src=/etc/passwd  dest=/tmp 
  - name: 
    file: path=/tmp/azure state=touch
  - name:
    apt: name=git state=present
         
