---
- hosts: 172.31.23.86
  become: yes
  vars:
     mydir: /tmp/balu
     myfile: /etc/passwd
     mypkg: 
       - apache2
       - wget
       - tree
  tasks:
  - name:
    file: 
      path: "{{ mydir }}"
      state: directory
 

  - name:
    apt: 
      name: "{{ mypkg }}"
      update_cache: yes
      state: present
  - name: 
    copy:
      src: "{{ myflie }}"    
      dest: "{{ mydir }}"
  