---
- hosts: all
  become: yes
  vars_files:
  - varibles/vars.yml
    
    
  tasks:
  - name:
    file: 
      path: "{{ mydir }}"
      state: directory
  - name: 
    copy:
      src: "{{ myfile }}"    
      dest: "{{ mydir }}"
  - name:
    apt: 
      name: "{{ mypkg }}"
      update_cache: yes

  